/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:495cc20c-7c86-4c46-8c62-a1ad0eea9470",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_zt3u1aCHq",
    "aws_user_pools_web_client_id": "5fasf26m0gjhrb5fa396r37obv",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "noteTable-staging",
            "region": "us-east-1"
        },
        {
            "tableName": "todosTable-staging",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "noteAPI",
            "endpoint": "https://xnl9t1m5ch.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        },
        {
            "name": "todosApi",
            "endpoint": "https://5jqbgohdf9.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
